name: ci

on:
  push:
    branches:
      - main

jobs:
  login-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Check variables
        run: |
          echo {{secret.DOCKERHUB_USERNAME}} && \
          echo {{secret.DOCKERHUB_TOKEN}}
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to myRegistry
        uses: docker/login-action@v3
        with:
          username: ${{ secret.DOCKERHUB_USERNAME }}
          password: ${{ secret.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tenpo:v1
