name: ci

on:
  push:
    branches: main

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name:
        run: |
            docker build . -t ${{secret.DOCKERHUB_USERNAME}}/pruebas:lastest
      - name:
        run: |
            docker loging -u ${{secret.DOCKERHUB_USERNAME}} -p {{secret.DOCKERHUB_TOKEN}}
            docker push ${{secret.DOCKERHUB_USERNAME}}/pruebas:lastest