name: Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        python-version: 3.10
    - name: Create env File
      run: |
          touch .env
          echo API_KEY={{secret.API_KEY}} >> .env
          echo MODEL_PATH="doubleit_model.pt" >> .env
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: pytest
